version: '3.8'

services:
  postgres-main:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lc_main
    ports:
      - "5432:5432"
    volumes:
      - pg_main_data:/var/lib/postgresql/data

  postgres-audit:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lc_audit
    ports:
      - "5433:5432"
    volumes:
      - pg_audit_data:/var/lib/postgresql/data

  ipfs:
    image: ipfs/kubo:latest
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ipfs_data:/data/ipfs

  besu:
    image: hyperledger/besu:latest
    command: ["--network=dev", "--rpc-http-enabled", "--rpc-http-cors-origins=*", "--rpc-ws-enabled", "--rpc-ws-cors-origins=*", "--miner-enabled", "--miner-coinbase=0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"]
    ports:
      - "8545:8545"
      - "8546:8546"

volumes:
  pg_main_data:
  pg_audit_data:
  ipfs_data:
